[[redirects]]
  from = "/*"
  to = "/pages/marketing/events/presentation.html"
  status = 200

[[redirects]]
  from = "/marketing/events/presentation"
  to = "/pages/marketing/events/presentation.html"
  status = 302

[[redirects]]
  from = "/marketing/hotels/presentation"
  to = "pages/marketing/hotels/presentation.html"
  status = 302

[[redirects]]
  from = "/marketing/restaurants/presentation"
  to = "pages/marketing/restaurants/presentation.html"
  status = 302

[[redirects]]
  from = "/marketing/training/presentation"
  to = "pages/marketing/training/presentation.html"
  status = 302

[[redirects]]
  from = "/marketing/university/presentation"
  to = "pages/marketing/university/presentation.html"
  status = 302

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
